name: aex fwb & telephony
on: push

jobs:
  job1:
    name: auto fwb & telephony
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: framework base
      continue-on-error: true
      run: |
       echo ok
    - name: framework opt telephony
      continue-on-error: true
      run: |
       echo ok
    - name: codeaurora telephony
      continue-on-error: true
      run: |
       echo ok
