name: aex fwb & telephony
on:
  workflow_dispatch:
jobs:
  job1:
    name: auto fwb & telephony
    runs-on: ubuntu-20.04
    env:
      password: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: git config
      run: |
       ./config
    - name: framework base
      run: |
       ./fwb
    - name: framework opt telephony
      run: |
       ./opt_telephony

  job2:
    name: auto crdroid vendor
    runs-on: ubuntu-20.04
    env:
      password: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: git config
      run: |
       ./config
    - name: crdroid vendor
      run: |
       ./crdroid
